### ISSUE TITLE
sandbox.osdcloud.com ssl error

### ISSUE THREAD

**Issue by khris91** [OSDeploy/OSDCloud#19]
When running the command "powershell.exe -executionpolicy bypass -command "iex(irm sandbox.osdcloud.com)" I get the error "irm : the underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel." 

This is being ran in WinPE

**Comment by OSDeploy** [comment]
Does it make a difference if you specify https?  powershell.exe -executionpolicy bypass -command "iex(irm https://sandbox.osdcloud.com)

**Comment by khris91** [comment]
Nope, same error sadly

**Comment by OSDeploy** [comment]
There are hundreds of articles on workarounds you can search for, I think this is outside the scope of OSDCloud
https://stackoverflow.com/questions/62934061/powershell-ssl-tls-error-with-invoke-restmethod-command

Are you running through a Proxy?
https://stackoverflow.com/questions/14263359/access-web-using-powershell-and-proxy

More information is needed, but this seems like it's on your end, otherwise this would fail for everyone

**Comment by khris91** [comment]
Looks like it's something specific to my WinPE instance, I gotta dig into it and figure out what's happening. Thank you for the help!

**Comment by khris91** [comment]
Just a heads up, weirdly enough I narrowed it down to it being the machine cause I tried the same WinPE boot drive on another machine and it worked. The machine affected is a Surface Pro 7. Not sure why it's giving that error but that's where I am at so far.
