### ISSUE TITLE
OSDCloud USB Not showing downloaded ESD

### ISSUE THREAD

**Issue by gnogeek** [OSDeploy/OSDCloud#23]
Hello I would like to report that on latest versions of osdcloud I downloaded two esd files using the download function for usb, but when I boot up the usb the downloaded are not reflected, thanks in advance. 
![image](https://user-images.githubusercontent.com/77178414/226746465-d386b9f0-8b2f-4fb6-b4fd-26d7aa5c9232.jpg)

Here OS’s aren’t listed.
![image](https://user-images.githubusercontent.com/77178414/226746883-f0f7e7ab-14f0-4d27-9296-6398b1213428.jpg)

**Comment by OSDeploy** [comment]
Downloaded ESD files that are downloaded and saved on the USB are not reflected in the GUI.  If you select a matching OS from the GUI that requires these ESD files, then the OS will be installed from the ESD files on the USB, rather than being downloaded again.  Were you expecting to see the ESD files in the list?
ISO files should be mounted if they meet certain conditions.

**Comment by gnogeek** [comment]
> Downloaded ESD files that are downloaded and saved on the USB are not reflected in the GUI. If you select a matching OS from the GUI that requires these ESD files, then the OS will be installed from the ESD files on the USB, rather than being downloaded again. Were you expecting to see the ESD files in the list?
> ISO files should be mounted if they meet certain conditions.

I’m going to give another try, I select one of the downloaded configs from drop-down menu, version and language but it downloads from internet anyways.
